
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import Header from '@/Components/Header'
import Footer from '@/Components/Footer'

const outfit = Outfit({ subsets: ["latin"] ,weight:["400","500","600","700"]});

export const metadata: Metadata = {
  title: "Open Learn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ToastContainer theme="dark" />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}